Dynamic Programming/Catalan-Numbers.cpp

A classic DP problem that is often asked in coding contests and interviews is solving for the nth Catalan number.  Catalan numbers have numerous applications, like possible number of expressions with correctly matched parentheses, possible number of BSTs with `n` keys, and so many more. [[Applications of Catalan Numbers - GeeksforGeeks]](https://www.geeksforgeeks.org/applications-of-catalan-numbers/)
Using the technique of **tabulation** in dynamic programming, I have written a program that computes and prints the first `n+1` Catalan numbers, where `n` is given by the user. 
Although Catalan numbers have a factorial-based definition, the definition I used was a recursive one. This definition is written in the program as comments (shown below), and also available in its [Wikipedia …

DP program: Catalan numbers

---

Math/Power_For_Huge_Num/Power_Huge.cpp

Added new Algorithms to compute power for such numbers whose answer is too big(For instance 1 followed by thousand zeroes).
Using old multiplicatiion method will render invalid result for such
huge numbers(To be presise one would get 0 in case of C++14).

Added new Algorithms to compute power for Huge Number

---

Graph/Topological-Sort.cpp

Added an implementation of Topological Sort for Directed Graphs.

Added Topological Sorting

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Add template for bug and feature as issue.
>Users can and should use these templates while creating any issues for the repository.

Add template for bug and feature as issue

---

dynamic_programming/tree_height.cpp

Added finding the height of the valid tree in O(n) using bottom - up dp approach.
where n is a number of nodes.
A valid tree contain exactly n-1 edges when n is number of nodes.
Sample Input: - 
4
1 2
1 3
2 3
Hence the height of the tree is 3
Notes:

Added tree_height.cpp in dynamic_programming directory

---

.github/workflows/sorting_non_recursive_merge_sort.yml

An attempt to fix the issues described at https://github.com/TheAlgorithms/TheAlgorithms.github.io/issues/1. This *should* publish the docs from the `C-Plus-Plus` repo to https://thealgorithms.github.io, but I have no way to test that this works correctly, as you could imagine.
Notes: An attempt to fix the issues described at https://github.com/TheAlgorithms/TheAlgorithms.github.io/issues/1.

fix: attempt to fix GH pages workflow

---

math/sqrt_double.cpp

Notes: 
Existing algo hangs on `Sqrt(0.5)`. Took advantage of equality `Sqrt(x) == 1/Sqrt(1/x)` to avoid evaluating small sqare roots.

fix: sqrt_double hangs on x < 1 (#760)

---

data_structure/doubly_linked_list.cpp

【memleak】when remove an item , should free the item memory

fix: doubly_linked_list.cpp bug

---

math/large_number.h

First of the fixes for #880 
Addresses the issues with `math/large_number.h` file:
* possible multiplication overflow 
* redundant `const` identifier for functions
* fix signed number check with 0
Notes:

bug fix: large number.h

---

data_structures/stack_using_array.cpp
data_structures/stack_using_linked_list.cpp
math/fibonacci_fast.cpp
others/paranthesis_matching.cpp

Various LGTM fixes - #880 
Notes:

fix: Various LGTM fixes

---

README.md

* Better description of the repository
* summary of features
* expanded documentation section
* added documentation license - #911 
Notes:

[improvement] update README with more details than a stub

---

CONTRIBUTING.md

Contribution guidelines updated with increased standards specs
Provides a sample code structure for reference
- ~[ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)~
- ~[ ] Added tests and example, test must pass~
- ~[ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)~
Notes:

[improvement] updated contribution guidelines

---

.clang-tidy
.github/workflows/awesome_workflow.yml

Disabled `clang-analyzer-cplusplus.Move` error to warning. 
See https://clang.llvm.org/extra/clang-tidy/checks/bugprone-use-after-move.html
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/948"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C-Plus-Plus.git/4e12f03c6cbfa42d7f77d06edd08e39cfb901f4b.svg" /></a>

[bug] disable move error + enforce c++11 for clang-tidy

---

machine_learning/adaline_learning.cpp
machine_learning/kohonen_som_topology.cpp
machine_learning/kohonen_som_trace.cpp
machine_learning/ordinary_least_squares_regressor.cpp
numerical_methods/newton_raphson_method.cpp
numerical_methods/ode_forward_euler.cpp

tidied up code based on error reports by clang-tidy
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/950"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C-Plus-Plus.git/042cd56a13aaf7891b10f980eb4ad274c25916ea.svg" /></a>

[cpp fixes] tidied up code based on error reports by clang-tidy

---

sorting/bogo_sort.cpp

Fixed an doxygen issue where algorithm was being described as ```pre```.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/960"><img src="https://gitpod.io/api/apps/github/pbs/github.com/imdeep2905/C-Plus-Plus.git/e0edf011c18b1d8c41b4d1579962420ca1e76020.svg" /></a>

docs: Fixed an issue in Bogo Sort documentation

---

math/least_common_multiple.cpp

Improving the least common multiple algorithm which unnecessarily caused an integer overflow since the two numbers were multiplied first and only then divided by the greatest common divisor. Using a common trick to first divide the first number with the common divisor and only multiply later. Adding a unit test to test this functionality.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/970"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/47974f0a72b0fa87ba02701b1374ab2f86c858dd.svg" /></a>

fix: Integer overflow of least_common_multiple.

---

graphics/CMakeLists.txt

Reverts TheAlgorithms/C-Plus-Plus#976
The checksum fail was due to Sourceforge being down.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/977"><img src="https://gitpod.io/api/apps/github/pbs/github.com/TheAlgorithms/C-Plus-Plus.git/4c597a46becd3c2fce76c1f68ec3df6c29cdbd3c.svg" /></a>

Revert "[bug] updated free glut checksum"

---

geometry/jarvis_algorithm.cpp

I implemented the Jarvis algorithm which, for a set of points in the plane, creates a convex hull of the points in the smallest convex polygon that contains all the points of it.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1027"><img src="https://gitpod.io/api/apps/github/pbs/github.com/rishabh-997/C-Plus-Plus.git/bf610fb91dad7f62aeee7c647ddf43dcbc0fe92e.svg" /></a>

Added Jarvis Algorithm to compute convex hull

---

DIRECTORY.md
dynamic_programming/shortest_common_supersequence.cpp

Closes #1029.
Definition: The Shortest Common Supersequence (SCS) is a string Z which is the shortest supersequence of two given strings X and Y (which may not be continuously present in Z, but order must be maintained).
example 1:
X: 'ABCXYZ', Y: 'ABZ' then Z will be 'ABCXYZ' (y is not continuous but in order)
example 2:
X: 'AGGTAB', Y: 'GXTXAYB' then Z will be 'AGGXTXAYB'
Notes:
There is an algorithm for finding LCS. We need an algorithm for SCS as well
PR for issue: #1029 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1030"><img src="https://gitpod.io/api/apps/github/pbs/github.com/ridhishjain/C-Plus-Plus.git/32ee52b41f3438b96aca7dfee4556b3963681ce6.svg" /></a>

feat: add shortest common super-sequence algorithm

---

sorting/pigeonhole_sort.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1028"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Lownish/C-Plus-Plus.git/4424320b075f885486b1a9c1440f278e4f7c075a.svg" /></a>

feat: add Pigeonhole algorithm

---

.clang-format
.github/workflows/awesome_workflow.yml
graph/is_graph_bipartite.cpp

Added explicit `clang-format` code and corresponding config file. Tested on other pull-requests where the formatting failed.
Closes #1032
Please see commit history for tests. I had to undo them but the actions will show that the execution works as expected.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1052"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C-Plus-Plus.git/c69cc5371a2485d75222596aa057a2aed28c3869.svg" /></a>

[bug fix] fix code formatting in CI

---

CONTRIBUTING.md

Aligning the instructions in [CONTRIBUTING.md](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md) to use the pre-defined style from [.clang-format](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/.clang-format) instroduced by #1052.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1053"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/594a3afc59a184d73f2c2e89737e13698895169e.svg" /></a>

docs: Update clang-format instructions in CONTRIBUTING.

---

greedy_algorithms/kruskals_minimum_spanning_tree.cpp

using namespace std is a bad practice
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1264"><img src="https://gitpod.io/api/apps/github/pbs/github.com/x0rld/C-Plus-Plus.git/38437e09b012036f0a8d09dcb14c4be745cba2e1.svg" /></a>

fix: remove `using namespace std` in greedy_algorithms/kruskals_minimum_spanning_tree.cpp

---

DIRECTORY.md
dynamic_programming/palindrome_partitioning.cpp

fixed: #1009
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1319"><img src="https://gitpod.io/api/apps/github/pbs/github.com/sujaykaushik008/C-Plus-Plus.git/67a043f910b67de5772be2a1c461253558f2ceb0.svg" /></a>

feat: add palindrome partitioning algorithm

---

data_structures/queue_using_array.cpp

Notes: 
In current version of `data_structures/queue_using_array.cpp` we have a really **bad bug (Resource leakage)** which is caused by using `new` operator without using `delete[]` after that ([Line 24](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/data_structures/queue_using_array.cpp#L24)); I fixed that by using `std::vector`. (If we want to still use C-Style array, just let me know and I will roll back to what we have now but I'll use `Smart Pointer` to fix that bug.)
Also I made some small refactoring to increase quality of code :)
If any thing need to be changed, just let me know that and after that it will be ready :)
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1428"><img src="https://gitpod.io/api/apps/github/pbs/github.com/farbodahm/C- …

[fix/docs]: Memory leakage caused by using `new` operator & refactoring/documentation

---

DIRECTORY.md
data_structures/tree_234.cpp

feat: add 2-3-4-tree implment
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1366"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fedom/C-Plus-Plus.git/37881226d6c532ae67504dc291c28cdbcb0f3bb4.svg" /></a>
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1366"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fedom/C-Plus-Plus.git/fa02c90722f9b5242068592f5f303f476858051f.svg" /></a>

feat: add 2-3-4-tree implment

---

DIRECTORY.md
search/saddleback_search.cpp

Added Saddleback search algorithm for 2D array.
Notes:
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1432"><img src="https://gitpod.io/api/apps/github/pbs/github.com/HashirGJ8842/C-Plus-Plus.git/d4fc405f0dcb9e851180ffef081e44c24301b127.svg" /></a>

feat: Add Saddleback search

---

LICENSE

- Single PR that updates the copyright year to 2021.
Notes:
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1440"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Panquesito7/C-Plus-Plus.git/fe76acf72a58e63b235d4cfc19724b6ae252d454.svg" /></a>

fix: Update copyright notice/year to 2021

---

DIRECTORY.md
data_structures/trie_using_hashmap.cpp

feat: Trie data structure using hashmap, predict_words method to recommend words based on a given prefix. 
Notes:

feat: Trie data structure using hashmap, predict_words method, class Trie

---

DIRECTORY.md
ciphers/base64_encoding.cpp
math/integral_approximation.cpp

Algorithm that takes in a lower bound, upper bound, function, and an optional delta value and computes an integral approximation.
Notes:

feat: added integral approximation algorithm

---

data_structures/linked_list.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1494"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Corrected erase method in `data_structures/linked_list.cpp`

---

sorting/cycle_sort.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1520"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

tests: Add test in `cycle_sort.cpp`

---

math/check_prime.cpp

Fix for Issue #1536 - [BUG] check_prime.cpp returns incorrect output for 9
- [x ] Added description of change
- [x ] Added tests and example, test must pass
- [x ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ x] I acknowledge that all my contributions will be made under the project's license.
Notes: Updating the check_prime.cpp. It was giving wrong output for n = 9
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1537"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Issue #1536 - [BUG] check_prime.cpp returns incorrect output for 9

---

hashing/chaining.cpp

I tried to make some additions in your file, thanks
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1559"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Add endlines in `hashing/chaining.cpp`

---

DIRECTORY.md
divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp
sorting/dnf_sort.cpp

Closes #1549
Added dnf sort.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1558"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add dnf sort

---

backtracking/magic_sequence.cpp

Add return 0; on main function.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1589"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Add `return 0` in `bactracking/magic_sequence.cpp`

---

.github/workflows/stale.yml

Set stale bot action limit to default because it's actually GitHub API action limit and not the number of issues/PRs it marks per run as I thought
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1607"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Unleash full power of the stale workflow

---

math/prime_numbers.cpp

Rewrite math/prime_numbers.cpp using linear sieve.
Notes: made change in math/prime_numbers.cpp
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1810"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: rewrite prime numbers using linear sieve

---

CODE_OF_CONDUCT.md

- Update the CoC (Code of Conduct) to match the `.github` repository.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1832"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Update the CoC to match the `.github` repository

---

DIRECTORY.md
dynamic_programming/partition_problem.cpp

Partition problem is to determine whether a given set can be partitioned into two subsets such that the sum of elements in both subsets is the same. 
Notes: This implementation has dynamic programming in it with the time complexity of **O(sum*n)** and space complexity of **O(sum*n)** where _sum_ is the sum of all the elements of vector
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1842"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Added Solution of Partition Problem

---

numerical_methods/gram_schmidt.cpp

Numerical methods already contains and uses linear algebra methods. Graham Schmidt doesn't need its own folder. I moved graham_schmidt.cpp to numerical_methods and deleted linear_algebra. An alternate option would be further compartmentalization of numerical methods into it's subjects: linear algebra, PDEs, etc.
Notes: 
This file was authored by @Akanksha-Gupta920 so I would prefer his input.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1940"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: move `gram_schmidt` to `numerical_methods`

---

DIRECTORY.md
math/modular_inverse_simple.cpp
math/power_of_two.cpp

Notes: 
this is a simple implementation made during a college course - discrete mathematics
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1937"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat : add modular_inverse_simple

---

CONTRIBUTING.md

Notes: 
There was a link broken in contributing file, under the contribution section. The link belongs to the MIT License. I've fixed it.

fix: fixed broken link in contributing file

---

.github/workflows/awesome_workflow.yml
.github/workflows/codeql.yml
.github/workflows/codeql_analysis.yml
.github/workflows/gh-pages.yml

- Fix Awesome Workflow issues.
- Thanks to @tjgurwara99 for the original fix: TheAlgorithms/C#1176
Notes:

feat: improve the Awesome Workflow

---

CONTRIBUTING.md

- Add a guide on integrating CMake.
- Taken from TheAlgorithms/C#1163.
Notes:

docs: add guide on integrating CMake

---

math/n_bonacci.cpp

This PR fixes the implementation of [`N_bonacci`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/4fc14710b60c265f265bd4d7c526207a5d477421/math/n_bonacci.cpp#L41), namely the result has always length equal to `m` and the case of `n == 0` is treated correctly.
Additional changes:
- fef05911cfd432864ef7efa27eed9c15244a0327 removes unused includes,
- ce85e26db138e3b7e1da093f169f35d1c5c920bc, a3d7134a09a1014b9b8b69364f5be0b30ae1f84d simplifies test and adds new test cases
- some minor updates of the comments
Notes: 
Fixes a bug in [`n_bonacci.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/4fc14710b60c265f265bd4d7c526207a5d477421/math/n_bonacci.cpp)

fix: cover the cases `n == 0` and `m < n` in `N_bonacci`

---

math/check_factorial.cpp

FIX: added namespace math, changed for a weird for loop to a while loop with a better conditional and I initiation
CHORE: Cleaned documentation and added details plus links. removed the invalid cout lines in test for one line.
Notes: clang-tidy check needed

fix:fit `check_factorial.cpp` to guidelines

---

.github/workflows/awesome_workflow.yml
.gitignore
scripts/file_linter.py

- Add the linter to a separate Python script to keep things cleaner.
- #2492 depends on this.
Notes:

chore: add the linter to a separate Python script

---

math/iterative_factorial.cpp

There is a memory leak in [`iterative_factorial.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/math/iterative_factorial.cpp) while throwing an exception. This PR fixes it and does some other small changes.
Notes: 
Removes memory leak in [`iterative_factorial.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/math/iterative_factorial.cpp).

fix: remove memory leak `iterative_factorial.cpp`

---

operations_on_datastructures/get_size_of_linked_list.cpp

[`get_size_of_linked_list.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/operations_on_datastructures/get_size_of_linked_list.cpp) has a memory leak. This PR adds the function `deleteList` in order to fix it.
Notes: 
Removes memory leak in [`get_size_of_linked_list.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/operations_on_datastructures/get_size_of_linked_list.cpp).

fix: remove memory leak `get_size_of_linked_list.cpp`

---

sorting/library_sort.cpp

There is a memory leak in [`library_sort.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/sorting/library_sort.cpp). This PR fixes it.
Notes: 
Remove memory leak in [`library_sort.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/sorting/library_sort.cpp).

fix: remove memory leak in `library_sort.cpp`

---

sorting/counting_sort.cpp

There are several problems with the current implementation of [`counting_sort.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/sorting/counting_sort.cpp):
- memory allocated by creating `*Count` is _uninitialized_ and not deleted,
https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/sorting/counting_sort.cpp#L29
- memory allocated by creating `*Sorted_Arr` is not deleted.
https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/sorting/counting_sort.cpp#L27
This PR fixes that.
Notes: 
This PR fixes _memory issues_ in [`counting_sort.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/sorting/counting_sort.cpp).

fix: memory issues in `counting_sort.cpp`

---

search/sublist_search.cpp

[`sublist_search.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/search/sublist_search.cpp) has a memory leak. This PR adds the function `deleteList` in order to fix it.
Notes: 
Removes memory leak in [`sublist_search.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/23b133ae1eac4ad7e94e74da140d462180738413/search/sublist_search.cpp).

fix: remove memory leak in `sublist_search.cpp`

---

math/ncr_modulo_p.cpp

The original implementation of [`NCRModuloP`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/0934ec4a8a0c58143776b9e8e0faf1ccc2ea88ed/math/ncr_modulo_p.cpp#LL31C7-L31C17), has two problems:
- the member variable [`fac`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/0934ec4a8a0c58143776b9e8e0faf1ccc2ea88ed/math/ncr_modulo_p.cpp#L43) is one element [too short](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGISRqkrgAyeAyYAHI%2BAEaYxBKSABykAA6oCoRODB7evv6BaRmOAqHhUSyx8VLJdpgOWUIETMQEOT5%2BAbaY9sUMjc0EpZExcQk1TS1teZ0KE4NhwxWj1QCUtqhexMjsHAD0AFT7JhoAggDU%2B2cAAjT0x%2BeXV9HEeJhUZwAqCHgKZynEqGAxFYZyYeBYvyYBDOoloyC8BkcRjOJgArBZssQziwMAjUPcLn80QARCAIAgEFIKEC7XbIFIAWjEwBIhAQEIAdGgWH …

fix: make interface of `NCRModuloP` fail-safe

---

math/extended_euclid_algorithm.cpp

It appears that gcc13 reordered some headers, so `iostream` no longer includes `cstdint`.
Files using `cstdint` via `iostream` need to be updated.
I've only changed one file, but there's sure to be more that need changing (see #2698).
Notes: For testing - https://godbolt.org/z/6WWh3zs9G

fix: compilation failure with gcc >= 13

---

sorting/bogo_sort.cpp

Fix deprecation warning for macOS:
```
[ 48%] Building CXX object sorting/CMakeFiles/bogo_sort.dir/bogo_sort.cpp.o
/Users/runner/work/C-Plus-Plus/C-Plus-Plus/sorting/bogo_sort.cpp:54:14: warning: 'random_shuffle<int *>' is deprecated [-Wdeprecated-declarations]
std::random_shuffle(arr.begin(), arr.end());// Shuffle the array
^
/Users/runner/work/C-Plus-Plus/C-Plus-Plus/sorting/bogo_sort.cpp:86:21: note: in instantiation of function template specialization 'sorting::randomized_bogosort<int, 5UL>' requested here
arr1 = sorting::randomized_bogosort(arr1);
^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__algorithm/shuffle.h:96:23: note: 'random_shuffle<int *>' has been explicitly marked deprecated here …
```

fix: fix deprecation warning for macOS

---

others/iterative_tree_traversals.cpp

[`iterative_tree_traversals.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/54a20b447efbdf56da7f331de7469e86d50f7dd5/others/iterative_tree_traversals.cpp) has a memory leak. This PR removes it.
Notes:

fix: remove memory leak from `iterative_tree_traversals.cpp`

---

others/recursive_tree_traversal.cpp

[`recursive_tree_traversal.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/db182d55217384912d7e837917d1dbc3ede45637/others/recursive_tree_traversal.cpp) has a memory leak (and does not compile). This PR fixes that.
Similar to #2720.
Notes:

fix: remove memory leak from `recursive_tree_traversal.cpp`

---

sorting/tim_sort.cpp

[`tim_sport`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/b6108e494dbd9ef05926fc5e8bc7f60147445ecb/sorting/tim_sort.cpp) has a _stack buffer underflow_. This PR fixes it and runs `clang-format` on this file.
Notes: 
Fixes memory issue in [`tim_sport`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/b6108e494dbd9ef05926fc5e8bc7f60147445ecb/sorting/tim_sort.cpp).

fix: stack buffer underflow in `tim_sort.cpp`

---

search/median_search2.cpp

[`median_search2.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/c652c4f2378275dc32c387148c2eaaf49b3f7bd7/search/median_search2.cpp) has a memory leak. This PR fixes it.
Notes: 
Fixes memory leak in [`median_search2.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/c652c4f2378275dc32c387148c2eaaf49b3f7bd7/search/median_search2.cpp).

fix: memory leak in `median_search2.cpp`

---

greedy_algorithms/huffman.cpp

Another quick fix of a memory leak. This time in [`huffman.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/15e3fed9248fbf2709e4dafec76728ef2c3b3d69/greedy_algorithms/huffman.cpp).
Notes: 
Removes a memory leak in [`huffman.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/15e3fed9248fbf2709e4dafec76728ef2c3b3d69/greedy_algorithms/huffman.cpp).

fix: memory leak in `huffman.cpp`

---

operations_on_datastructures/reverse_binary_tree.cpp

This PR adds a destructor to [`BinaryTree`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/7828b8e238ecff9b13f2ac4c4b863ece0e917981/operations_on_datastructures/reverse_binary_tree.cpp#L52). Furthermore the _copy constructor_ and the _assignment operator_ was explicitly deleted in order to... _simplify things_.
Notes: 
Removes the memory leak from [`reverse_binary_tree.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/7828b8e238ecff9b13f2ac4c4b863ece0e917981/operations_on_datastructures/reverse_binary_tree.cpp).

fix: remove memory leak from `reverse_binary_tree.cpp`

---

greedy_algorithms/kruskals_minimum_spanning_tree.cpp

Added the test cases for  greedy_algorithms\kruskals_minimum_spanning_tree.cpp issue #2509 
Notes: Added the test cases in greedy_algorithms\kruskals_minimum_spanning_tree.cpp to validate edge cases.

Added test cases in greedy_algorithms\kruskals_minimum_spanning_tree.cpp

---

data_structures/circular_queue_using_linked_list.cpp

[`circular_queue_using_linked_list.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/920b6d4e81c041f03b385a1f042f0260d4be3e50/data_structures/circular_queue_using_linked_list.cpp) has a memory leak and it is not formatted properly. This PR fixes that.
Notes: 
Fixes the memory leak in [`circular_queue_using_linked_list.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/920b6d4e81c041f03b385a1f042f0260d4be3e50/data_structures/circular_queue_using_linked_list.cpp).

fix: remove memory leak from `circular_queue_using_linked_list.cpp`

---

greedy_algorithms/huffman.cpp

Continuation of #2728 (I wanted to minimize the scope of the change there).
Notes: 
Basic linting.

style: lint `huffman.cpp`

---

bit_manipulation/gray_code.cpp

Create a Gray code generation algorithm under bit_manipulation.
Notes:

feat: Create gray_code.cpp

---

search/binary_search.cpp

making some correction in the theory of binary search
mentioning the space complexity

docs: reword binary search

---

strings/duval.cpp

Added the implementation of Duval's Algorithm for finding the lexicographically smallest cyclic shift of a sequence. The algorithm is based on the concept of Lyndon words and works in O(n) time, making it efficient for this type of task. This implementation is generic and works with various sequence types, such as strings, vectors, arrays, and deques.

feat: add duval's algorithm

---

math/area.cpp

Added the area of hemi-sphere algorithm with test to math/area.cpp 
Notes:

feat: Add hemi-sphere area algorithm 

---

math/gcd_of_n_numbers.cpp

Adding documentations, tests, and amending the algorithm to align with current guidelines.
Notes: 
The current algorithm is not accurate and also does not account for 0 in the array, especially when GCD is undefined if all elements are 0.

fix: Adding documentations, tests, and amending algorithm for gcd_of_n_numbers.cpp

---

others/lfu_cache.cpp

LFU Cache implementation
In a fixed size cache, when new item is added and the cache is full
The least frequently used element is evicted from the cache
If there are multiple items with the same frequency of usage,
then the least recently used item is evicted.
Notes: 
added LFU Cache with tests and usage.

feat: LFU (Least frequently used) cache

---

math/fibonacci.cpp

Adding and updating existing documentation and tests for the algorithm to align with current guidelines.
Notes: 
fixed fibonacci.cpp according to issue #2456

fix: Update documentations and tests for fibonacci.cpp

---

sorting/bubble_sort.cpp

- Add namespaces, tests and documentations according to current guidelines.
- Generalising data type for bubble sort algorithm so that the algorithm can be applied to an array of any data type.
Notes: 
For Hacktoberfest, for #2456

docs, test: Fit bubble_sort into guidelines and enhance bubble sort algorithm

---

math/modular_inverse_fermat_little_theorem.cpp

Reformat math/modular_inverse_fermat_little_theorem.cpp by adding namespaces, documentations, tests.
Notes: 
For Hacktoberfest, for #2456

docs, test: fit modular inverse fermat little theorem to contributing guidelines

---

others/lru_cache2.cpp

LRU Cache implementation
In a fixed size cache, when new item is added and the cache is full
The least recently used element is evicted from the cache
Notes: 
added LRU Cache with tests.

feat: LRU (Least recently used) cache - different implementation

---

.github/workflows/approved-label.yml
.github/workflows/awesome_workflow.yml

This reverts commit 41653de7183f12d5eab9fc4077125836f42e6c96.
Notes:

Revert "chore: use annotations instead of in house linter (#2905)"

---

ciphers/uint256_t.hpp
data_structures/stack_using_array.cpp
data_structures/tree_234.cpp

This PR resolved the `-Wreorder` warning emitted by the compiler.
Notes: 
This PR resolved the `-Wreorder` warning.

style: resolve `-Wreorder`

---

search/linear_search.cpp

This PR solves the _array index out of bounds_ problem. When `size` changes, the `array` has to be relocated.
Notes: 
Fix _array index out of bounds_ problem in `linear_search.cpp`.

fix: resize `array` to avoid `arrayIndexOutOfBounds`

---

range_queries/prefix_sum_array.cpp

Observe that in the _old code_, because the `<=` is used in the loop, there is an _index out of bounds_ error. The main reason for this PR is to fix this problem. The rest is just _fix as you go_:
- `std::size_t` should be used for _indexing_ standard containers,
- the api is slightly more intuitive now (consider calling the `build` function twice in the old code). 
Notes: 
Fix _one-off_ error leading to _index out of bounds_.

fix: use strict inequality to avoid `containerOutOfBounds`

---

physics/ground_to_ground_projectile_motion.cpp

Notes: Introduced GRAVITY constant (9.80665 m/s²) for consistent use across physics algorithms.

Added constexpr GRAVITY constant (9.80665) as per guidelines

---

math/factorial_memoization.cpp

[`factorial_memoization.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/63aa8595cd209cd525abbe0f9c318bd7fbb074ea/math/factorial_memoization.cpp) has a potential segmentation fault: consider the call like `fact_recursion(1000)`.
This PR fixes that and additionally removes one global variable. @git5v: please have a look.
Additionally I decided to remove the `math` namespace, because it is a cpp file with a `main` function anyway.
@realstealthninja: regarding the doc-strings: we have different opinion about them. If you will find some additional one useful, please just push it to my branch.
Notes: 
Removes a potential segv.

fix: remove potential segv from `factorial_memoization`

---

others/postfix_evaluation.cpp

The [`Stack`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/43ce63682a087b17e01b945aaa3fa7a51c36f82c/others/postfix_evaluation.cpp#L32) class has _fixed_ capacity and can store up to 20 elements. This might lead to a segmentation fault. This PR fixes that, i.e.:
- adds a test, which causes the old code to fail.
- it replaced the `Stack` class by [`std::stack`](https://en.cppreference.com/w/cpp/container/stack.html).
Similar to #2994.
Notes: 
Removes a potential segv.

fix: remove potential segv from `postfix_evaluation.cpp`

---

others/postfix_evaluation.cpp

Since the input size of [`postfix_evaluation`](https://github.com/vil02/C-Plus-Plus/blob/3aafade824d9f615fcf63b3f22fe8d6f7652fec0/others/postfix_evaluation.cpp#L88) is a template parameter, this function needs to be compile for every used input size (this increases both the build time and the size of the binary).
This PR changes the the type of the input to `std::vector` to avoid such problem.
Notes: 
Use `std::vector` as input type, to avoid increase of build time and binary size.

refactor: input size should not be a template argument in `postfix_evaluation`

---

bit_manipulation/count_of_set_bits.cpp

Updated the `countSetBits` function in bit_manipulation/count_of_set_bits.cpp to improve **type safety and correctness**:  
- Changed the input parameter from `int64_t` to `uint64_t` to ensure only non-negative numbers are allowed.  
- Changed the internal counter variable `count` from `int` to `uint64_t` to match the return type and prevent any theoretical overflow.  
- Maintains original functionality for normal inputs.
This ensures the function is consistent, safe, and fully aligned with the intended use of counting set bits in non-negative integers.
---
---
**Notes:**  
Improves type safety for `countSetBits` function without changing its behavior for normal inputs.

Fix: use uint64_t for input and counter in countSetBits

---

scripts/file_linter.py

File formatter always exits early becuase of unreachable code, Intially while copying this script from the workflow file(#2500) the indentation was not proper
removed the unneccessary indentation
Notes:

chore: fix file formatter

---

.github/workflows/codeql.yml

CodeQL V2 has been [deprecated](https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/)
Notes: bumped v2 -> v3

ci: bump codeql to v3
