Computer Oriented Statistical Methods/Gaussian_elimination.cpp

Added Gaussian Elimination method. Thats written in cpp.

added gaussian elimination method

---

Binary Search.cpp

Add Binary Search

---

Dynamic Programming/Fibonacci_Bottom_Up.cpp
Dynamic Programming/Fibonacci_Top_Down.cpp

Generate nth Fibonacci number - Top Down and Bottom Up DP approach

Add DP implementations

---

Dynamic Programming/Longest Increasing Subsequence.cpp

Add Longest Increasing Subsequence

---

fibonacci.cpp

Using Divide and Conquer.
This algorithm takes T = O(logn) time which is quite small as compared to the traditional method which takes O(n).
This is my first commit so any constructive criticism is always welcome.

Added an algorithm for finding nth term of fibonacci sequence.

---

Happy_number.cpp

Don't code when drunk or test it.

Fix happy number algorithm.

---

sieve_of_Eratosthenes.cpp
ternary_search.cpp

Added the iterative and recursive method for the ternary search algorithm.

Ternary Search Algorithm

---

Math/Prime_Factorization/README.md
Math/Prime_Factorization/primefactorization.cpp

Prime Factorization of a number is added under the math folder.

Prime Factorization of a number

---

Sorting/Tim Sort.cpp

Tim Sort Algorithm is based on radix sort & bubble sort.
It's stable algorithm which works in O(n Log n) time, is used in Java's Array.sort(). It first sorts using small pieces, later sorts each with merge sort.

Tim Sort.cpp

---

Decimal to Roman Numeral.cpp

added test cases and main function as requested.
removed bits/stdc++.h and added only the necessary headers as requested

Added Decimal to Roman Numeral Converter

---

Primality Test.cpp

removed bits/stdc++.h as suggested.
added brackets as suggested.

Add Primality Test

---

Others/fibonacci.cpp

Implemented an easier to implement and faster algorithm than the already present matrix exponentiation method to find nth fibonacci number.
This is faster than matrix exponentiation method as it is a DP form of matrix exponentiation.
Faster than O(logn)

Updated logic of fibonacci.cpp

---

Others/Decimal to Roman Numeral.cpp

copied the file from 
C-Plus-Plus/Decimal to Roman Numeral.cpp
to
C-Plus-Plus/Others/Decimal to Roman Numeral.cpp
directory to facilitate organizing as other Decimal to binary, hexadecimal etc are in this directory.

Decimal to Roman Numeral.cpp

---

fibonacci.cpp

Updated this file similar to the directory
C-Plus-Plus/Others/fibonacci.cpp

Updated logic of fibonacci

---

Linear Search.cpp

Linear Search was returning key instead of index. Fixed it.
Changed array from size 10 to variable sized.
Same changes like the linear search in different directory.

Fixed Linear Search

---

Others/String Fibonacci.cpp

This programme uses String Addition to find Nth fibonacci.

Added String Fibonacci

---

Search/Linear Search.cpp

Previous programme was returning key instead of index. Fixed it.
Changed array size from 10 to user defined size.

Rectified Linear Search

---

Sorting/Slow Sort.cpp

added the main function as requested.
added only the necessary header as requested.
Description of Slow Sort can be found here 
https://en.wikipedia.org/wiki/Slowsort

Added SlowSort

---

Sorting/CocktailSelectionSort.cpp

Cocktail Selection Sort is a Sorting algorithm which chooses the minimum and maximum element in an array simultaneously, and swaps it with the lowest and highest available position iteratively or recursively

Added Cocktail Selection Sort

---

NumericStringSort.cpp

Sorts an array of Numeric strings.
An array of strings like 1,2,3,10,20,30,100,200,300 are sorted as 1,10,100,2,20,200,3,30,300 Conventionally.
This programme sorts them in the correct numeric order i.e 1,2,3,10,20,30,100,200,300

Added Numeric String Sort

---

Dynamic Programming/Bellman-Ford.cpp
Dynamic Programming/Floyd-Warshall.cpp
Greedy Algorithms/Dijkstra.cpp

Added Dijkstra's shortest path algorithm in Greedy Algorithm Directory

Add Shortest path Algorithms

---

Dynamic Programming/Edit Distance.cpp

Added Edit Distance Algorithm in Dynamic Programming

Edit Distance Algorithm

---

Backtracking/Rat_maze.cpp

A rat starts from source and has to reach destination. The rat can move only in two directions: forward and down.
In the maze matrix, 0 means the block is dead end and 1 means the block can be used in the path from source to destination. 
We have to print any one possible pass path from source to destination.

Add code for Rat maze problem in backtracking.

---

Math/Prime_Factorization/primefactorization.cpp

My computer doesn't seem to have the stdc++.h, so I tried changing it to the two headers really used. It seems to be solving the problem.

Edits #include directives

---

smallest-circle.cpp

https://en.wikipedia.org/wiki/Circumscribed_circle

naive algorithm for the circumscribed circle

---

Sorting/Bubble Sort.cpp

I have modified the bubble sort to now use a vector instead of the standard array. The bubble sort now supports sorting a list of any user defined size, and now uses the built in function std::swap. Finally, the output now is comma separated, except for the final element, which is just ended with a newline. Attached you can view an example output of the program.

Bubble Sort now uses vectors

---

Dynamic Programming/Edit Distance.cpp

Fixes #100. Also fixes 2 other bugs in the implementation of `editDist` and `editDistDP`.

Fix bugs in edit distance implementation

---

Sorting/Insertion Sort.cpp

n is the size of the input array. It is declared in the code but not defined a value or taken as input. It is fixed by simple `cin>>n;` addition.

n is now taken as an input.

---

Datastructures/Linked List.cpp

Added EXIT option in the menu for getting out of the loop and added lines between printing the list and choices for fine-tuning the output.

Added EXIT option and some fine-tunings

---

Sorting/Bubble Sort.cpp
Sorting/Insertion Sort.cpp

-introduced variable 'swap' for 'outer-for-loop' of bubble sort algorithm. If it remains zero after executing inner-loop, it means array is sorted, hence it does not need to run for n^2 times.
- 'for(int j=0; j<n-1-i; j++)', as after each step of 'outer-loop', one number reaches to its right position. Thus inner loop does not need to run for 'n' times in every cycle of 'outer-loop'.

Optimize bubble sort algorithm, solve run time error in insertion sort

---

Others/Paranthesis Matching.cpp

Fixed issue #168 + some tweaks

Update Paranthesis Matching.cpp

---

Datastructures/Linked List.cpp

Fixed issue #175 + add **Exit** option

Fixed Linked List.cpp

---

Datastructures/linkedList_implentation_usingArray.cpp

I have added this new implementation of linked list using arrays , without using pointers and dynamic allocation of memory.

added a new implementation of linked list

---

Palindromeofnumber.cpp

Added the algorithm to convert number to string and check if it's a palindrome.

Added and algorithm to check if a number is palindrome

---

Sorting/CountingSortString.cpp

Implemented a counting sort for string in cpp

Implemented sort for string

---

Dynamic Programming/Coin-Change.cpp
Dynamic Programming/Matrix-Chain-Multiplication.cpp

Added two more Standard Problems Coin Change and Matrix Chain Multiplication to Dynamic Programming.

added Dynamic Programming Problems

---

Data Structure/Linked List.cpp

reversing a linked list is one of the very famous interview question, so I thought it would be helpful.

Added reverse function to linked list

---

Data Structure/Queue Using Linked List.cpp

Because of earlier logic not going to deque the last element of the queue because at the last front == rear as per your logic which directly results in "Underflow".

Update in Deque() fuction

---

Dynamic Programming/Fibonacci_Bottom_Up.cpp

' Generally, it takes linear space for the problem but we can reduce space to linear to constant.
'

Space Optimization for the code - Constant Space

---

Sorting/Bubble Sort.cpp

Removed unnecessary usage of break and restored the single entry and single exit mechanism

Update Bubble Sort.cpp

---

Search/Interpolation Search.cpp

<h1>Description</h1>
Interpolation is an English word which means analyzing value of function by analyzing value at near points.
Considering the meaning of Interpolation, this search algorithm is based on the principle of attempting to look for a key in a list of elements, by comparing the key (value to be searched) with specific elements at "calculated positions" and ensuring if the key occurs "before" it or "after" it until either the key is found or not found.
The elements in the array must be in sorted order(increasing).

Added Interpolation Search algorithm inside search folder

---

Dynamic Programming/Longest Increasing Subsequence (nlogn).cpp
Graph/lca.cpp
Range queries/bit.cpp

LCA using Binary Lifting.
[Resource ](https://cp-algorithms.com/graph/lca_binary_lifting.html)

Added Binary Lifting O(nlogn) method to find Lowest Common Ancestor

---

Dynamic Programming/Longest Increasing Subsequence (nlogn).cpp
Graph/lca.cpp
Range queries/bit.cpp

Binary Indexed Tree.
Resources : 
- [Video Tutorial ](https://www.youtube.com/watch?v=v_wj_mOAlig) About basic idea
- [Explanation](https://cs.stackexchange.com/a/10541) Why does it work [Visual Example](https://cs.stackexchange.com/a/42816)

Added Binary Indexed Tree and O(nlogn) LIS

---

Data Structure/Linked List.cpp

This  instruction terminator is invalid here.

Update Linked List.cpp

---

Backtracking/knight-tour.cpp
Dynamic Programming/longest_common_string.cpp

added 2 new algorithms please have a look

added knight tour to backtracking and longest common string to dynamic

---

.github/pull_request_template.md
CONTRIBUTION.md
README.md

Added Changes to Readme file, moved contribution guide to the CONTRIBUTION.md file with much more details and information and guidelines. Also added pull-request-template.md to .github folder which should be automatically used and displayed to the user in the current PR's format.
Notes: 
These files contains links to each other. The links should be active as soon as the PR is merged, the link is created in the place where the file is going to be placed after the pull request.

Feat: Add/Format Readme.md Contribution.md and pull-request-template.md

---

README.md

The 'contribution guidelines' link is incorrectly linked, so I fixed it with the correct link.
Notes:

I modified a link(Contribution guidelines)

---

Range queries/FenwickTree.cpp

FenwickTree also named as Binary-Indexed-Tree. It organizes data using binary characteristics.
Point Update and Range Query can all be done with O( log (n) ) , and has less hidden constant than Segement-Tree.
What's more, Range Update and Point Query can be done with FenwickTree , I will pr as soon as i finish it, also ST , matrix quick pow .
I'm glad if you can give me some suggestions with my first pr   :-)

Added FenwickTree For Range Query

---

.github/workflows/ccpp.yml

GitHub Action to run cpplint on all pull requests

---

Backtracking/knight_tour.cpp

Add information about the file for brief intro and changed the file name to correct 
Notes:

bugfix Update and rename knight-tour.cpp to knight_tour.cpp

---

.github/workflows/cpplint_modified_files.yml
.github/workflows/validate_new_filenames.yml
Others/happy_number.cpp

Add cpplint to validate_filenames

---

Operations on Datastructures/matrix_layer_rotation.cpp
Others/PlayfairCipher.cpp

Contributors guide: https://github.com/TheAlgorithms/C-Plus-Plus/CONTRIBUTION.md
-->
Notes: 
this algorithm rotates the layers of matrix. (layer means frame of matrix, 4 sides)
algorithm goes inside by layer by layer and rotate it.

Matrix rotation algorithm

---

String/knuth_morris_pratt.cpp

- Calculate whether the given pattern exist in the given text.
- Return true if it finds a match.
- Otherwise return false.

Added knuth pratt morris algorithm for finding string match.

---

.github/pull_request_template.md
CONTRIBUTION.md

Added new file name guidelines, the new contribution needs to be in certain format to be used for the dynamic directory list generator. The file names will be validated using the actions in near future.
Notes: 
The old file names will be changes soon with one directory at a time.
The old PR might need some re-work.

feat - Add new file name guidelines

---

CONTRIBUTION.md

Add cpplint to CONTRIBUTION.md
Notes:

doc: Add cpplint to CONTRIBUTION.md

---

.github/workflows/cpplint_modified_files.yml

GitHub Action: Compile modified files with g++

---

search/hash_search.cpp

hash_search.cpp

---

data_structure/trie_tree.cpp

trie_tree.cpp: #include <string.h> --> <string>

---

math/fast_power.cpp

Implemented algorithm that computes a^b in O(logN) time recursively or linear.

Add fast power

---

data_structure/cll/cll.cpp
data_structure/cll/cll.h
data_structure/cll/main_cll.cpp
data_structure/cll/makefile

Add simple circular linkedlist

---

sorting/heap_sort.cpp

heapsort implementation started at index 1

---

data_structure/disjoint_set.cpp

Add Disjoint Set in data_structure

---

math/eulers_totient_function.cpp

In _Number Theory_, **Euler's Totient Function** counts the positive integers up to given integer n that are relatively prime to n. It is written using the Greek letter _phi_ as φ(n) or ϕ(n), and may also called Euler's Phi Function. In other words, it is the number of integers k in the range 1<= k <= n for which the greatest common divisor gcd(n,k) is equal to 1.
This algorithm is implemented in O(sqrt(n)) time complexity and O(1) space complexity respectively.
This algorithm follows like this: - 
phi(n) = phi(p1^a1) * phi(p2^a2)...
where p1, p2,... are prime factor of n.
3 Euler's Property:
1. phi(prime_no) = prime_no-1
2. phi(prime_no^k) = (prime_no^k - prime_no^(k-1))
3. phi(a,b) = phi(a) * phi(b) where a and b are relative primes.
Applying this 3 property on the first equation. …

Added Eulers Totient Function in math directory

---

math/binary_exponent.cpp

Binary Exponentiation is the method to calculate the a^n (where '^' denotes the power operator). This will find a^n in just O(log(n)) complexity instead O(n) multiplication. The idea behind this algorithm is it will convert the exponent into binary which came up with exactly log(n)+1 digits in base 2.
Example: -
2^10 = 2^(1010) = 2^8 * 2^2
2^1 = 2
2^2 = (2^1)^2 = 2^2 = 4
2^4 = (2^2)^2 = 4^2 = 16
2^8 = (2^4)^2 = 16^2 = 256
Hence to calculating 2^10 we only need to multiply 2^8 and 2^2 skipping 2^1 and 2^4.

Added Binary Exponentiation in math directory

---

math/greatest_common_divisor_euclidean.cpp

Notes: 
An implementation of greatest common denominator using the Euclidean algorithm.

feat: add euclidean algorithm implementation of gcd

---

.github/workflows/sorting_non_recursive_merge_sort.yml
DIRECTORY.md
sorting/doxy.txt
sorting/makefile
sorting/non_recursive_merge_sort.cpp

Add the source file (sorting/non_recursive_merge_sort.cpp) which defines the function template "non_recursive_merge_sort" in different forms, along with a helper function merge. Moreover, it creates 2 additional files, doxy.txt for Doxygen configuration, and a makefile to automate building, testing and cleaning. This address [issue #728](https://github.com/TheAlgorithms/C-Plus-Plus/issues/728).

Add file for non-recursive merge sort

---

.github/workflows/sorting_non_recursive_merge_sort.yml
probability/addition_rule.cpp

Created 'probability' folder and added addition_rule.cpp which calculates the OR of two probabilities.
for independent probabilities:
P(A∪B) = P(A) + P(B) – P(A∩B)
for dependent probabilities:
P(A∪B) = P(A) + P(B) – (P(A) * P(B|A)
Notes:

feat: added addition_rule.cpp for probability

---

operations_on_datastructures/get_size_of_linked_list.cpp

Added a function to get the size of a linked lists in the file get_size_of_linked_list.cpp. 
Checklist

feat: added a function to get the size of a linked list

---

graph/connected_components.cpp

Added `connected_components.cpp` in `graphs`
finding the connected components in undirected graphs (implemented using DFS)

Connected Components using DFS

---

math/fibonacci.cpp

Notes: 
This is a simple implementation of fibonacci's sequence

Fibonacci funtion added

---

graph/connected_components_with_dsu.cpp

feat: add algo to find no of connected components with Union Find Structure

---

probability/poisson_dist.cpp

The poisson distribution counts how many events occur over a set time interval
Notes:

feat: added poisson_dist.cpp

---

strings/rabin_karp.cpp

Implemented Rabin Karp Algorithm for string matching.
function rabin_karp will take two string type parameters "str"{text} and "pat" {pattern} and will return -1 if no pattern match found otherwise return index of first pattern match index.

feat: added rabin_karp algorithm for string match

---

computer_oriented_statistical_methods/ordinary_least_squares_regressor.cpp

Linear regression of input data using ordinary least squares method. 
* Inputs
* F and N = number of input features and training sample number
* N rows, each of F samples and corresponding 1 sample output
* T = number of test samples (0 for none)
* T rows, each of F samples
* Outputs
* T rows of estimates
Tests: works on all test samples from [here](https://www.hackerrank.com/challenges/predicting-house-prices/problem).
Notes: Linear regressor using ordinary least squares method.

linear regression using ordinary lease squares

---

probability/binomial_dist.cpp

the binomial distribution models the number of successes in a sequence of n independent events
Notes:  nCr method may be needed in other scripts

feat: added binomial_dist.cpp

---

probability/bayes_theorem.cpp

Created bayes_theorem.cpp which allows one to find P(A|B) given P(B|A) and P(A) and P(B)
Notes:

feat: created bayes_theorem.cpp

---

CONTRIBUTION.md

This habit makes us slow and chatty so let’s discourage it.
Notes:

CONTRIBUTING.md: Don’t open issues asking to be assigned

---

graph/bridge_finding_with_tarjan_algorithm.cpp

Fixes #783
Added Bridge finding with Tarjan's Algorithm.

feat : bridge finding with tarjan algorithm

---

graph/max_flow_with_ford_fulkerson_and_edmond_karp_algo.cpp

fixes #790 
Implemented the Ford-Fulkerson method with Edmond Karp Optimization.

feat : find maximum flow in a graph

---

data_structure/trie_modern.cpp

The older implementation has very big memory leaks as there is no delete operation for the raw pointers used and assigned. The newer implementation uses modern c++ code and solves the memory leak issue too. I have tried to document the code as well as I could have.
Notes: Modernize code and fix memory leaks of trie data structure.

feat: Modern trie code with better memory management

---

math/miller_rabin.cpp

I added a simple implementation of Miller-Rabin primality test.
Notes:  Implementation of Probabilistic Miller-Rabin Primality Test.

feat: Added a probabilistic Miller-Rabin Primality Test

---

math/pythagoras.cpp

Description of Change
Add implementation of pythagoras distance algorithm. #829 
Checklist
-[ ] Added description of change
Added file name matches File name guidelines
Added tests and example, test must pass
Relevant documentation/comments is changed or added
PR title follows semantic commit guidelines
Search previous suggestions before making a new one, as yours may be a duplicate.
Sort by alphabetical order
I acknowledge that all my contributions will be made under the project's license.
implement pythagoras distance. style cling format.

Implement pythagoras distance algorithm.

---

machine_learning/adaline_learning.cpp
machine_learning/kohonen_som_topology.cpp
numerical_methods/newton_raphson_method.cpp
numerical_methods/ordinary_least_squares_regressor.cpp

* Updated documentation of code
* Increased accuracy limit for newton-raphson method
Notes:

[docs] fixed documentations

---

math/sum_of_digits.cpp

Added a file ``sum_of_digits.cpp`` in the ``math`` folder which computes the sum of the digits of an integer.

feat: add sum of digits

---

DIRECTORY.md
numerical_methods/brent_method_extrema.cpp

Algorithm to find minima of a unimodal univariate real function in a given interval. 
Notes:

feat: Brent's method to find extrema

---

.vscode/settings.json
DIRECTORY.md
numerical_methods/golden_search_extrema.cpp

1. Added algorithm to obtain maxima and minima of a continuous univariate real function in a given interval using golden section search algorithm.
2. Enable `AlignConsecutiveMacros` in clang-format settings of vscode.
Notes:

[feat:] Minima algorithm

---

data_structures/list_array.cpp
data_structures/trie_tree.cpp

Part of effort for #880 
*Errors fixed*: Two files reported function with return types but missing return statements without checks. 
Notes:

[bug fix] errors reported by lgtm

---

math/complex_numbers.cpp

A class implementation of complex numbers along with all permitted field operations and some additional complex number specific operations.
Notes:  Class implementation of complex numbers.

Feat: Class implementation of complex numbers along with most complex number operations.

---

math/check_amicable_pair.cpp

Added a file check_amicable_pair.cpp in the math folder which checks the pair is amicable or not.
Notes:

feat: add check_amicable_pair.cpp

---

data_structures/binary_search_tree.cpp
math/realtime_stats.cpp
sorting/bead_sort.cpp
sorting/comb_sort.cpp

Various LGTM fixes. - #880 
Notes: Will work on to fix more LGTM issues.

fix: Various LGTM fixes

---

data_structures/stack.h

Part of fixes for #880 : `data_structures/stack.h`
* should have a copy constructor matching the assignment operator
* replaced `NULL` with more appropriate `nullptr`
* added documentation 
Notes:

Bug: LGTM issue with missing copy constructor

---

sorting/heap_sort.cpp

fix: minor docs issue

---

others/matrix_exponentiation.cpp

Part of effort in #880 
Fixes global variables in `matrix_exponentiation.cpp`. The program execution, input and output is unknown.
Notes:

bugs: fix warnings in matrix_exponentiation

---

graph/connected_components.cpp
sorting/heap_sort.cpp

Added documentation
Earlier i implemented this file but at that time i did not added the docs
Notes:

Added docs to graph/connected_components.cpp

---

math/double_factorial.cpp

Part of effort for #880. Refer problem reported in #897 and corresponding [lgtm link](https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/rev/pr-f6e7cda8faf908e87511f30e782190233bdee68c)
* Fixes unsigned comparison to `0`
* adds self-tests
Notes:

bug fix: fix self-tests and unsigned comparision to zero

---

DIRECTORY.md
numerical_methods/lu_decompose.cpp
numerical_methods/lu_decomposition.h

* Applied LU decomposition algorithm to a separate header file
* define and use matrix type
* added determinant computation using LU decomposition
Notes:

enhancement: LU decompose to header file and self-tests

---

numerical_methods/lu_decompose.cpp
numerical_methods/lu_decomposition.h

removed `@brief` tags from function docs. `@brief` should be used only if there is a corresponding `@details` tag. Otherwise, the associated code doesn't get compiled in the docs.
Notes:

[doc] fix documentation in lu_decompose

---

numerical_methods/ordinary_least_squares_regressor.cpp

Added missing self-test cases for OLS regressor implementation.
Notes:

[fix] added test cases to OLS Regressor

---

sorting/insertion_sort.cpp

* Comments made in #929  fixed
* added function overload
* included function in namespace `sorting` for consistency
Notes:

[fixes] issues from #929

---

math/complex_numbers.cpp

Tried to fix some documentation issues that @kvedala pointed out in #884.
Notes:  Documentation fix

docs: fixed some documentation issues

---

math/sieve_of_eratosthenes.cpp

Improved `sieve_of_eratosthenes.cpp` by looping till sqrt(N).
Notes: Code change in `sieve_of_eratosthenes.cpp`

Improved sieve_of_eratosthenes.cpp

---

search/fibonacci_search.cpp

Implementation of Fibonacci search with an example of its usage in main function
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/942"><img src="https://gitpod.io/api/apps/github/pbs/github.com/sprintyaf/C-Plus-Plus.git/58099884dd626ba94602fa00351d8e6c5f49c9e9.svg" /></a>

Added Fibonacci search

---

.github/workflows/awesome_workflow.yml

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/949"><img src="https://gitpod.io/api/apps/github/pbs/github.com/TheAlgorithms/C-Plus-Plus.git/024db9fe6c2dfcc84e72ec06ba4f5cff015e7a22.svg" /></a>

[error] Fix command syntax

---

data_structures/queue_using_two_stacks.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/953"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shoniavika/C-Plus-Plus.git/acfe6751237f69578a63c8e4cbea07a0bc7f0630.svg" /></a>

Added queue implementation using two stacks

---

ciphers/caesar_cipher.cpp

Added Caesar Cipher as ciphers/caesar_cipher.cpp
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/957"><img src="https://gitpod.io/api/apps/github/pbs/github.com/imdeep2905/C-Plus-Plus.git/3a4cfae70958493183f950955c56fc1becbe6975.svg" /></a>

feat: add Caesar Cipher

---

math/sieve_of_eratosthenes.cpp

Several improvements of this implementation
- Slight improvement of the algorithm (only eliminate multiples of the prime from p^2) -> time complexity O(N log log N)
- Using C++ std vector to return the list of results
- Inverting the logic for `is_prime` such that `true` represents (intuitively) primes
- Adding a unit test
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/969"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/8abcd4b3a59b7168f54c34077fb8b35b20f28dc5.svg" /></a>

fix, test: Refactor of sieve_of_eratosthenes

---

.gitpod.dockerfile

Install `freeglut3-dev` in GitPod Docker image.
- ~[ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)~
- ~[ ] Added tests and example, test must pass~
- ~[ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)~
- ~[ ] Relevant documentation/comments is changed or added~
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/973"><img src="https://gitpod.io/api/apps/github/pbs/github.com/TheAlgorithms/C-Plus-Plus.git/1524a63c7c27a158cffb2e4702d884456a37ae0b.svg" /></a>

[enhancement] add freeglut3-dev to build and view OpenGL programs 

---

graphics/CMakeLists.txt

The MD5 checksum of free glut-3.2.1 release has changed. The CMake needs to be updated to fix this.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/976"><img src="https://gitpod.io/api/apps/github/pbs/github.com/TheAlgorithms/C-Plus-Plus.git/5ed427cbe1bd20f68b79026ac8443d6e7af6c40c.svg" /></a>

[bug] updated free glut checksum

---

graphics/CMakeLists.txt

This reverts commit 09d47709f87af94462bc7f1f9fabe27822e27df6.
The checksum on the source forge repo has been resolved.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/979"><img src="https://gitpod.io/api/apps/github/pbs/github.com/TheAlgorithms/C-Plus-Plus.git/4c597a46becd3c2fce76c1f68ec3df6c29cdbd3c.svg" /></a>

Revert "updated free glut checksum (#976)"

---

math/number_of_positive_divisors.cpp

- The function was not actually implemented according to the description and didn't handle negative inputs correctly (it was only checked in the main function).
- The function unnecessarily created a vector of numbers only to multiply them later, these numbers can be multiplied as you go.
- Fixed a typo in the description.
- Adding some unit tests.
Notes: 
A small refactor of this module.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/975"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/c2f20882fb8237c03784722f3c99f449b39f6ce0.svg" /></a>

fix, test: simplification and tests for number_of_positive_divisors

---

graph/bridge_finding_with_tarjan_algorithm.cpp

Splitting off from #954 (@ayaankhan98)
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/991"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/135d93b18fc43643db607a4717c6ffdecbd46cc7.svg" /></a>

fix: linter warnings for bridge finding algorithm.

---

graph/topological_sort_by_kahns_algo.cpp

Splitting up from the original commit from #954 (@ayaankhan98)
Note that there's no CI for this folder yet.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/993"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/c6ddee6b288b68d81880589d052a398b7a4e197c.svg" /></a>

fix: linter warnings for topological_sort_by_kahns_algo

---

graph/connected_components_with_dsu.cpp

Splitting of from #954 (@ayaankhan98)
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/992"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/26b5b2e2399b65f9139034be38422967e38d37fc.svg" /></a>

fix: linter warnings for connected_components_with_dsu.

---

graph/topological_sort.cpp

Splitting up from the original commit from #954 (@ayaankhan98)
Note that there's no CI for this folder yet.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/994"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/6e149d96573b38a7d77f06334202245b725ba0b8.svg" /></a>

fix: linter warnings for topological_sort.

---

graph/prim.cpp

Splitting up from the original commit from #954 (@ayaankhan98)
Minimal set of changes to pass CI.
Note that there's no CI for this folder yet.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/998"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/e5ba4691306ffa205914bae01e0f33633a67f54b.svg" /></a>

fix: linter for prim.

---

graph/max_flow_with_ford_fulkerson_and_edmond_karp_algo.cpp

Splitting up from the original commit from #954 (@ayaankhan98)
Note that there's no CI for this folder yet.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/997"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/d383443ae335f471859393532e0817b565323de0.svg" /></a>

fix: linter for max flow.

---

backtracking/n_queens.cpp

- Improve `backtracking/n_queens.cpp` with better code and documentation
- Continuation of #916
Notes: 🎉This is the 1000th issue/PR! 🎉 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1000"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Panquesito7/C-Plus-Plus.git/8454057249a29aa4e2d7cf795e22a6e551009043.svg" /></a>

[fix/docs]: Improve backtracking/n_queens.cpp

---

graph/lowest_common_ancestor.cpp

Fix small spelling typo: `@rerturns` --> `@returns`
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1024"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Panquesito7/C-Plus-Plus.git/e1bebe71529191682ab0053a02f6115f3f21c7fa.svg" /></a>

fix: spelling typo

---

graph/is_graph_bipartite.cpp

Added an algorithm is_graph_bipartite.cpp which determines whether the given graph is a bipartite graph or not.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1018"><img src="https://gitpod.io/api/apps/github/pbs/github.com/AkVaya/C-Plus-Plus.git/fd6b8100614e97b30056eb48744cb4fc8cbd32b9.svg" /></a>

Added is_graph_bipartite.cpp

---

math/fibonacci.cpp

- Added a test function for the fibonacci() function.
Notes: 
A simple test function was added to test the fibonacci() function to make sure that the results are correct.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1023"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fzxutar/C-Plus-Plus.git/cc64ca66b0cb6a25f7a820c5747b12669a538263.svg" /></a>

test: add test for fibonacci() function

---

graph/dijkstra.cpp

Split off from #986 .
Note, does not run CI yet (blocked by #986)
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1033"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/c1961d7c2ba7ddc82c55f40ad40e1317dc2f1bc5.svg" /></a>

fix: linter for dijkstra

---

graph/connected_components.cpp

Split off from #986 .
Note, does not run CI yet (blocked by #986)
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1034"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/2c41598e379f746dc91bd28d8a64c8c3e7bcf839.svg" /></a>

fix: linter for connected_components.

---

graph/kruskal.cpp

Split off from #986 .
Note, does not run CI yet (blocked by #986)
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1036"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/feb2237343d98e08bde1d3549213c0130ce55d8d.svg" /></a>

fix: linter for kruskal

---

graph/kosaraju.cpp

Split off from #986 .
Note, does not run CI yet (blocked by #986)
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1035"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/1b19ac99bd47c6357fea66a15e2f27ee5ace83b0.svg" /></a>

fix: linter for kosaraju

---

CONTRIBUTING.md
DIRECTORY.md

Updated guidelines to state that a new implementation should not over-write existing code but be added as an additional file with a numeric suffix
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1051"><img src="https://gitpod.io/api/apps/github/pbs/github.com/TheAlgorithms/C-Plus-Plus.git/02bef6b70b411173ba18fadb419ae80ff7f295e6.svg" /></a>

[enhancement] guideline for multiple implementations

---

DIRECTORY.md
math/fibonacci.cpp

as title
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1047"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/04d97400306e4702ff857a0aad602f1c5afa3a17.svg" /></a>

fix: math/fibonacci linter warnings.

---

graph/dijkstra.cpp

`clang-format --style="file" graph/dijkstra.cpp -i`
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1055"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/944f229dde517c6770cbe4896a35b47952a72e77.svg" /></a>

fix: clang-format for dijkstra

---

graph/hamiltons_cycle.cpp

`clang-format --style="file" graph/hamiltons_cycle.cpp -i`
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1054"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/3c9ee3321f688bc8db6c986459aef486e8304480.svg" /></a>

fix: clang-format for hamiltons_cycle.

---

strings/knuth_morris_pratt.cpp

Corrected the typo in the file.
- [*] Added description of change
- [*] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [*] I acknowledge that all my contributions will be made under the project's license.
Notes: Corrected the typo in the file
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1058"><img src="https://gitpod.io/api/apps/github/pbs/github.com/raman08/C-Plus-Plus.git/10efd07432d68df9c2408b87948e8b94b0dc516e.svg" /></a>

docs: Corrected the typo in the file

---

.clang-tidy
data_structures/trie_tree.cpp

**Clang Tidy**
Remove `performance-unnecessary-value-param` as error but keep as warning because `clang-tidy` can auto-fix it.
**Trie Tree**
* Fixed general code quality
* ISO C++11 standard conformity
* added documentation
* fixes LGTM alert
* Closes #1057 
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1059"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C-Plus-Plus.git/7529612b1b694927495a17754ac4f2d0a306b13f.svg" /></a>

[code fix] Fixed trie_tree for code quality and docs & clang-tidy error check

---

data_structures/skip_list.cpp
data_structures/trie_tree.cpp

rename `data_structure` namespace to `data_structures`.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1061"><img src="https://gitpod.io/api/apps/github/pbs/github.com/kvedala/C-Plus-Plus.git/3a0f8fe18020b6644d10339b56f8f7a403f3e3db.svg" /></a>

[fix] rename data_structures namespace

---

CONTRIBUTING.md

I believe the code sample in the CONTRIBUTING file should meet the highest standards to give a good example.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1063"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/52f79a707cffcaf8264e8f83bb65077d15eb606c.svg" /></a>

docs: Clean up of code examples in CONTRIBUTING to follow guidelines.

---

strings/CMakeLists.txt
strings/horspool.cpp

- [x ] Added description of change
- [x ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x ] Added tests and example, test must pass
- [x ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x ] Relevant documentation/comments is changed or added
- [x ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x ] I acknowledge that all my contributions will be made under the project's license.
Notes: 
An implementation of …

Added Horspool algorithm

---

graph/breadth_first_search.cpp

Aiming to unify the graph data structure that is used across the graph algorithms. #1004 Piloting it on the BFS algorithm.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1076"><img src="https://gitpod.io/api/apps/github/pbs/github.com/fhlasek/C-Plus-Plus.git/5fdf13c2c7628272a9651375b2f4b29eedfaf7e5.svg" /></a>

feat: Define graph structure in breadth_first_search

---

sorting/merge_sort.cpp

Here, I have shorten the code. There are three while loop used in merge function. Among which two of them can be replaced by adding a condition for if and while of first while loop. Now, the condition for while: (i < n1 || j < n2) and for if: (j>=n2 || (i < n1 && L[i]<R[j])).
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1066"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Himalay12/C-Plus-Plus.git/e9d940587e4472ccaaea7da84f1b6e105233cd6f.svg" /></a>

Merge sort

---

DIRECTORY.md
others/postfix_evaluation.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1083"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Darshana-Sarma/C-Plus-Plus.git/fa00f0f0664d49d67020247ea4f5b68671ef075a.svg" /></a>

feat: Added Postfix Evaluation

---

data_structures/stack_using_array.cpp

Added bottom function for getting bottom element from a stack .
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1137"><img src="https://gitpod.io/api/apps/github/pbs/github.com/pratamjain/C-Plus-Plus.git/29a0221fba79736f9d465d58ab979c77ddb0601d.svg" /></a>

Updated stack_using_array.cpp

---

.vscode/settings.json
DIRECTORY.md
math/check_factorial.cpp

Added a check_factorial algorithm under math.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1155"><img src="https://gitpod.io/api/apps/github/pbs/github.com/divyajyotiuk/C-Plus-Plus.git/a52c8aa3303896b42b46f0f58b43af1577437661.svg" /></a>

feat: added check_factorial

---

machine_learning/neural_network.cpp

Fixed a typo in the file ```neural_network.cpp``` . Changed **kernal** to **kernel**.
Notes:

fix: Fixed a typo in neural_network.cpp

---

backtracking/sudoku_solve.cpp

Updated the comments in [backtracking/sudoku_solve.cpp](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/backtracking/sudoku_solve.cpp) from Hindi to English language. 
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1273"><img src="https://gitpod.io/api/apps/github/pbs/github.com/sauravUppoor/C-Plus-Plus.git/6e3495004a20ea72d75fcd4416aed5a2d0e6afe4.svg" /></a>

docs: Update comments to English in sudoku_solve.cpp

---

CODE_OF_CONDUCT.md

- Added Code of Conduct.
Notes: Code of Conduct from the https://github.com/TheAlgorithms/.github repository.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1135"><img src="https://gitpod.io/api/apps/github/pbs/github.com/TheAlgorithms/C-Plus-Plus.git/c48e03e08c07e0c3c0bbef025758b379a4af8118.svg" /></a>

[fix/feat]: Added Code of Conduct

---

backtracking/rat_maze.cpp

- Improve [`backtracking/rat_maze.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/backtracking/rat_maze.cpp) with refined code and documentation.
Notes:
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1084"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Panquesito7/C-Plus-Plus.git/9b5b1db0a3dd66c0f53ad70a95bd93d202c5caad.svg" /></a>

[fix/docs]: Improve backtracking/rat_maze.cpp

---

backtracking/sudoku_solve.cpp
dynamic_programming/word_break.cpp
machine_learning/neural_network.cpp

Adding dynamic programming approach for the famous Word Break problem which has been frequently asked in FAANG interviews.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1278"><img src="https://gitpod.io/api/apps/github/pbs/github.com/axayjha/C-Plus-Plus.git/8be01a113d70b8ca767d507168c69ee3bbea90cf.svg" /></a>

adding word break DP approach

---

DIRECTORY.md
sorting/pancake_sort.cpp

- [x ] Added description of change
- [x ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x ] Added tests and example, test must pass
- [x ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x ] Relevant documentation/comments is changed or added
- [x ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x ] I acknowledge that all my contributions will be made under the project's license.
Notes: 
<a …

feat: Add Pancake Sort algorithm

---

dynamic_programming/0_1_knapsack.cpp

added documentation in `dynamic_programming/0_1_knapsack.cpp`
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1207"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Pardeep009/C-Plus-Plus.git/a72a98820de6f0b02ea0429d793758ffdbb26a90.svg" /></a>

added documentation in `dynamic_programming/0_1_knapsack.cpp`

---

machine_learning/neural_network.cpp

As seen in #1322, added similar description for the main function in the file ```neural_network.cpp```.  
->
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1331"><img src="https://gitpod.io/api/apps/github/pbs/github.com/imdeep2905/C-Plus-Plus.git/9c32e7851f1e2a2830167688ed32d2d26b66cb06.svg" /></a>

docs: Imporoved Documentation in neural_network.cpp

---

CONTRIBUTING.md

- Improve `CONTRIBUTING.md` with better understanding/explanation.
Notes:
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1300"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Panquesito7/C-Plus-Plus.git/42c733b958d4cfcd928076c174b2f087a7a84ec7.svg" /></a>

[fix/docs]: Improve CONTRIBUTING.md

---

DIRECTORY.md
ciphers/morse_code.cpp

Added Morse Code as ```ciphers/morse_code.cpp```.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1322"><img src="https://gitpod.io/api/apps/github/pbs/github.com/imdeep2905/C-Plus-Plus.git/60d22a3b9107e5e824fea43bafd120ae7d4c6e2f.svg" /></a>

feat: Added Morse Code

---

DIRECTORY.md
sorting/cycle_sort.cpp

Added the code for Cycle sort algorithm.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1252"><img src="https://gitpod.io/api/apps/github/pbs/github.com/dalaoqi/C-Plus-Plus.git/54dfb0118c8b4fb56bb0419551503aa137bb37bf.svg" /></a>
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1252"><img src="https://gitpod.io/api/apps/github/pbs/github.com/dalaoqi/C-Plus-Plus.git/ec24321e5f8902b039e1d20c581203bc20ec2a8a.svg" /></a>

feat: add cycle sort algorithm

---

graph/breadth_first_search.cpp

Modified the `graph/breadth_first_search.cpp` file to include wider range or inputs by creating a generic class
1. Replaced the namespace with a generic class Graph
2. Created add edge function to account for both directional and bidirectional graph
3. test case to include string nodes also
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1359"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Gpamangkp/C-Plus-Plus.git/f763e8d13773efac82477cd8a1695784655c320e.svg" /></a>

Modified the source for wider range of inputs

---

DIRECTORY.md
math/lcm_sum.cpp

An algorithm to calculate the sum LCM(1,n) + LCM(2,n) + .. + LCM(n,n), where LCM(i,n)
denotes the Least Common Multiple of the integers i and n. For n greater than or equal to 1.
The value of the sum is calculated by the formula:
∑LCM(i, n) = ((∑(d * ETF(d)) + 1) * n) / 2
Examples 1 :
LCM sum of 2 = 4
Examples 2 :
LCM sum of 5 = 55
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1344"><img src="https://gitpod.io/api/apps/github/pbs/github.com/chestamittal/C-Plus-Plus.git/2d415763d7f456fc5313bee05dfe746e4614dd67.svg" /></a>

feat: add lcm_sum.cpp

---

DIRECTORY.md
math/magic_number.cpp
sorting/pancake_sort.cpp

This Pull Request is for HacktoberFest 2020
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1318"><img src="https://gitpod.io/api/apps/github/pbs/github.com/neha-hasija17/C-Plus-Plus.git/806f3251ee483a4f31b4ec4dd7e1f645a79630e9.svg" /></a>

feat: Create magic_number.cpp

---

DIRECTORY.md
greedy_algorithms/kruskals_minimum_spanning_tree.cpp
math/sum_of_binomial_coefficient.cpp

An Algorithm to find the sum of binomial coefficients for a given positive integer.
The sum of binomial coefficients for a given n is calculated by the formula 2^n. 
Example 1-
n=2 
sum=2^2=4
Example 2-
n=4
sum=2^4=16
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1363"><img src="https://gitpod.io/api/apps/github/pbs/github.com/muskan0719/C-Plus-Plus.git/8993bb233c8e8ce160ccffdff0e6afe26297d6a1.svg" /></a>

feat: add sum_of_binomial_coefficients

---

DIRECTORY.md
sorting/wiggle_sort.cpp

Added Wiggle Sort algorithm implementation. Wiggle Sort sorts the array into a wave like array. An array ‘arr[0..n-1]’ is sorted in wave form, if arr[0] >= arr[1] <= arr[2] >= arr[3] <= arr[4] >= …..
Notes: Used Vectors instead of arrays for the implementation of the program.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1265"><img src="https://gitpod.io/api/apps/github/pbs/github.com/roshan0708/C-Plus-Plus.git/0ebacc6bceca3f77488268d54a94f9e747e968ca.svg" /></a>

feat: add wiggle sort algorithm

---

numerical_methods/false_position.cpp

- Updated [`numerical_methods/false_position.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/numerical_methods/false_position.cpp) method that can find multiple roots.
- Improve [`numerical_methods/false_position.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/numerical_methods/false_position.cpp) with refined code and documentation.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1321"><img src="https://gitpod.io/api/apps/github/pbs/github.com/sampatil578/C-Plus-Plus.git/930083964c86eec7f684fbc4200cbd9de63a5615.svg" /></a>

feat/fix: Improve numerical_methods/false_position.cpp

---

dynamic_programming/kadane.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1364"><img src="https://gitpod.io/api/apps/github/pbs/github.com/18JE0782/C-Plus-Plus.git/f3e5c1cfb909c1deb28555ff4aee90855b02b42c.svg" /></a>

Optimized code

---

backtracking/sudoku_solve.cpp
numerical_methods/rungekutta.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1286"><img src="https://gitpod.io/api/apps/github/pbs/github.com/rudraprasaddas/C-Plus-Plus.git/dcad20d828d85599d033b68f32116d5fac628bac.svg" /></a>

feat: Add Runge Kutta Method

---

DIRECTORY.md
linear_algebra/gram_schmidt.cpp

Added code for Gram Schmidt Orthogonalisation.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1339"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Akanksha-Gupta920/C-Plus-Plus.git/97105528645ccde24273fbbae088b0e8df02c486.svg" /></a>

feat: Add Gram Schmidt Orthogonalisation

---

DIRECTORY.md
math/n_choose_r.cpp

Added a simple n choose r combinatoric function.
Notes:  Added a simple n choose r combinatoric function.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1429"><img src="https://gitpod.io/api/apps/github/pbs/github.com/tjgurwara99/C-Plus-Plus.git/32f780d942ac9169160381f2fb6e40f26b8bafa1.svg" /></a>

Feat: added n_choose_r combinatorics algorithm

---

DIRECTORY.md
math/largest_power.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1406"><img src="https://gitpod.io/api/apps/github/pbs/github.com/uday6670/C-Plus-Plus.git/d5c896aa3a0ff4842480a11f1524a4a6e0ec62fe.svg" /></a>

feat: largest_power

---

DIRECTORY.md
sorting/count_inversions.cpp
sorting/radix_sort2.cpp

Counts the number of inversions in a list using merge sort. The number of Inversions in a list is the measure of the list's proximity to being sorted in ascending/increasing order.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1425"><img src="https://gitpod.io/api/apps/github/pbs/github.com/rakshitraj/C-Plus-Plus.git/e0a887ed243ae7b72e7d750b78d6c89df54d3e60.svg" /></a>
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1425"><img src="https://gitpod.io/api/apps/github/pbs/github.com/rakshitraj/C-Plus-Plus.git/047578bb0ab390573e769381fcf2429c150dd8a4.svg" /></a>

feat: Add sorting/count_inversions.cpp

---

backtracking/sudoku_solve.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1438"><img src="https://gitpod.io/api/apps/github/pbs/github.com/urbanij/C-Plus-Plus.git/ba602e48040a38dbd30a514dc7e5fbcfabfbb905.svg" /></a>

feat: added highlighting differences in Sudoku Solver

---

DIRECTORY.md
math/modular_division.cpp

Program to find the division of two numbers under modulo p (p is a prime number).
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1441"><img src="https://gitpod.io/api/apps/github/pbs/github.com/shubhamamsa/C-Plus-Plus.git/a4f830b90be32c66645174a33fae3808e906cb3a.svg" /></a>

feat: added modular division algorithm

---

dynamic_programming/cut_rod.cpp

if all the price are same then we can do it in o(n).
improved time complexity.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1388"><img src="https://gitpod.io/api/apps/github/pbs/github.com/ABHISHEK-821005/C-Plus-Plus.git/2cc9100f83738d9011d1301218adbadbfc2038e3.svg" /></a>

fix: updated datatypes references

---

math/fibonacci_matrix_exponentiation.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1215"><img src="https://gitpod.io/api/apps/github/pbs/github.com/villayatali123/C-Plus-Plus.git/e7de95c959a1576ec52e8e05baefba72db335e05.svg" /></a>

Nth fibonacci number using matrix exponentiation

---

CODE_OF_CONDUCT.md
math/vector_cross_product.cpp

This program calculates the cross product of two mathematical vectors.
The direction ratios of the two vectors are passed into two array using ``std::cin`` and the direction ratios of the cross product (which is also a vector) are given out along with the magnitude of the cross product.
Notes: 
Latex code has not been used because I am not familiar with it and the formula is simple enough to be understood as it is without latex code. 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1292"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Shreyas-OwO/C-Plus-Plus.git/b43ef498822e21d975c6a2d39940bf6e20a04b12.svg" /></a>

cross product of two vectors

---

data_structures/list_array.cpp

https://github.com/TheAlgorithms/C-Plus-Plus/issues/1373
- Documentation added.
- Wrote the test cases for all the methods with edge cases.
- Fixed the bugs in various methods.
- Refined the code.
- Efficiency improved.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1375"><img src="https://gitpod.io/api/apps/github/pbs/github.com/sagarpandyansit/C-Plus-Plus.git/4ba90633cb9b7dce803cbe7b172107804f3e225b.svg" /></a>

[docs/test]: Documentation and test in the list_array.cpp

---

DIRECTORY.md
data_structures/binary_search_tree.cpp
data_structures/binary_search_tree2.cpp

Add new implementation of binary search tree code using oop, generics, and smart pointers.
Add basic documentation to each of the BST functions.
Add tests for each BST function.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1208"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Walt280/C-Plus-Plus.git/248daf0fa2cc4fcf0a9c9470d17c6f629d9ba5ae.svg" /></a>

feat: add new implementation of binary search tree

---

graph/depth_first_search_with_stack.cpp

Fixes:
- Added namespace `graph`
- Generalised variable data types from `int` to `size_t`
- Added `addEdge()` function for uniformity with other graph algorithms.
Tests:
- Added 3 test cases.
Docs:
- Added documentation throughout the code.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1335"><img src="https://gitpod.io/api/apps/github/pbs/github.com/sauravUppoor/C-Plus-Plus.git/b3f67a1caba5b0cb8df3edb2c48ed6a243336582.svg" /></a>

fix/test/docs: update variable sizes, add namespace in graph/depth_first_search_with_stack.cpp

---

.github/stale.yml

Configure/setup [Probot Stale](https://github.com/marketplace/stale).
Notes: App has been already installed, so the only thing missing is to add the `stale.yml` file. 🙂

feat: Setup Probot Stale app

---

sorting/comb_sort.cpp

fix: Updated sorting/comb_sort.cpp

---

Data Structure/RBTree.cpp

feat: Create RBTree.cpp

---

DIRECTORY.md
math/linear_recurrence_matrix.cpp

feat: Solving linear recurrence using Matrix Exponentiation (with examples).
[Reference for the topic](https://www.hackerearth.com/practice/notes/matrix-exponentiation-1/).
Notes:

feat: Solving linear recurrence using Matrix Exponentiation (with examples).

---

DIRECTORY.md
dynamic_programming/Minimum Edit Distance.cpp
dynamic_programming/minimum_edit_distance.cpp

feat: Added Minimum Edit Distance Algorithm

---

.github/workflows/awesome_workflow.yml
DIRECTORY.md

Updated the awesome_workflow.yml to download the [build_directory_md.py](https://github.com/TheAlgorithms/scripts/blob/main/build_directory_md.py) from the [scripts](https://github.com/TheAlgorithms/scripts) repo. This makes it easier to make changes to it, since now almost all repositories use it.
~Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)~
~Added tests and example, test must pass~
~Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)~
~Relevant documentation/comments is changed or added~
Notes:

feat: update awesome_workflow.yml to use build_directory_md.py from scripts repository

---

.vscode/settings.json
sorting/recursive_bubble_sort.cpp

I recently contributed to [Algorithms-Explanation](https://github.com/TheAlgorithms/Algorithms-Explanation) repository and added the explanation for `Recursive Bubble Sort`. I further decided to add implementation for the same and used the existing `bubble_sort.cpp` as a reference to write my code.
Notes: 
Recursive implementation of `bubble_sort.cpp`
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1487"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Added Recursive Bubble Sort 

---

data_structures/circular_queue_using_linked_list.cpp

Description: 
-Resolved read violation in function dequeue and traverse.
-Removed some unused variables
-Resolved some warnings reported by Sonar 
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1496"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: read violation resolved

---

DIRECTORY.md
data_structures/sparse_table.cpp

Added implementation of sparse table for any 'duplicate invariant function'. Implementation of min(a1,a2...,aN) being the duplicate invariant function is done. Sparse tables are useful data structures to answer ranged queries in O(1), with precomputation of O(N*log(N)).
Implementation in `sparse_table.cpp` contains insightful comments and abides the Doxygen standards.
Notes: 
The implementation function can be 'hot swapped' by changing just 2 lines of code, so the implementation of sparse table for min() queries becomes sparse table for gcd().
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1502"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add spare table data structure

---

dynamic_programming/longest_increasing_subsequence.cpp

- Improve the `dynamic_programming/longest_increasing_subsequence.cpp` file.
- Added documentation, made the code up to the repository standards, and made the CI stop failing.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1504"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[feat/fix/docs]: Improve the `dynamic_programming/longest_increasing_subsequence.cpp` file

---

CONTRIBUTING.md

- Improve the contributing guidelines.
- Mostly fixes grammar, spelling errors, typos, and improves wording.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1503"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[feat/fix]: Improve the contributing guidelines

---

CONTRIBUTING.md
CodingGuidelines.md

- Improve the contributing guidelines, and add the `CodingGuidelines.md` file, taken and edited from the [C](https://github.com/TheAlgorithms/C) repository.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1522"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

[feat/fix]: Guidelines improvements

---

DIRECTORY.md
sorting/random_pivot_quick_sort.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1510"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add random pivot quick sort algorithm

---

backtracking/graph_coloring.cpp

Replace "\n" -> std::endl
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1530"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Replace "\n" -> std::endl

---

DIRECTORY.md
dynamic_programming/house_robber.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1524"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Add House Robber algorithm

---

DIRECTORY.md
sorting/wave_sort.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1525"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Add the Wave Sort algorithm

---

DIRECTORY.md
operations_on_datastructures/inorder_successor_of_bst.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1532"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: add inorder successor for bst in operations on ds

---

search/floyd_cycle_detection_algo.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1540"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Add the floyd_cycle_detection_algo.cpp file/algorithm

---

DIRECTORY.md
backtracking/graph_coloring.cpp
backtracking/subarray_sum.cpp
others/iterative_tree_traversals.cpp
sorting/random_pivot_quick_sort.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1527"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Add the Subarray Sum implementation

---

DIRECTORY.md
backtracking/wildcard_matching.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1552"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Wildcard matching problem

---

DIRECTORY.md
divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp

Fixes issue #1507 
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1550"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Karatsuba algorithm

---

README.md

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1560"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Minor spelling fixes in `README.md`

---

DIRECTORY.md
math/inv_sqrt.cpp

Add inverse inverse root functions (Template version)
- **Fast_InvSqrt** : C++ version of fast inverse square root implementation.
- **Standard_InvSqrt** : The fast inverse square root with standard lib (cmath).
All function are template function and C++11.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1570"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Add inverse inverse root functions

---

README.md

Fixed typo
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1582"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Fixed typo in README.md

---

.github/workflows/stale.yml

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1648"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat: Update stale workflow message

---

.gitpod.yml

- Update Gitpod extensions.
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1839"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: Update Gitpod extensions

---

DIRECTORY.md
numerical_methods/babylonian_method.cpp

Babylonian method is used to calculate  square roots .
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1837"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

feat : Implemented Babylonian Method

---

data_structures/linked_list.cpp

When learning about the linked list data structure implementation in cpp, I found a tiny typo in the code at file `data_structures/linked_list.cpp`, line 37, so I just fix it directly and open a pull request.
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1843"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: a typo in `data_structures/linked_list.cpp`

---

strings/brute_force_string_searching.cpp

For the comment "// use this for MS Visucal C++"
Changed "Visucal" to "Visual".
Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1853"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix: spelling mistake for "Visual"

---

CONTRIBUTING.md

Fixed Typos
Notes: 
Fixed typos in words reasonable and formatting
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1932"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fixed typos

---

sorting/merge_sort.cpp

Notes: 
<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1938"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

fix a small typo

---

CONTRIBUTING.md

- Improve the contributing guidelines.
Notes:

docs: improve the contributing guidelines

---

sorting/quick_sort_3.cpp

- Fix `quick_sort_3.cpp` warning.
Notes:

fix: `quick_sort_3.cpp` warning

---

divide_and_conquer/karatsuba_algorithm_for_fast_multiplication.cpp

doc: improved comments
Fixes #2086. There are two problems found:
1. Wrong usage of `std::to_string`. This function outputs the ASCII value of `char` instead of converting char bit to string. A fix (among many other ways) is to replace it with `std::string::insert`.
2. Since string '0' is not equal to '00', '000', ..., base case of algorithm `if (n == 1) {` may not be reached. The fix is to create a function named `safe_substr` that is used to carefully split the bit string with consideration to leading zeros.  
Notes:

fix: karatsuba's algorithm is not compiling

---

dynamic_programming/kadane2.cpp

Remove a whitespace at the beginning of the doxygen documentation comment in kadane2.cpp file. #2271 
Notes:

fix: fix markdown formatting

---

dynamic_programming/0_1_knapsack.cpp
dynamic_programming/armstrong_number.cpp
dynamic_programming/longest_increasing_subsequence_(nlogn).cpp

Notes: 
Grammatical errors and typo has been fixed.
Contribution made under hacktoberfest 2022.

docs: fix grammatical errors and typos

---

sorting/merge_sort.cpp

Fixed a logically wrong deoxygenated comment:
The second subarray should be defined for m + 1 to r ( from the next element after middle index, to the last index of original array)
Notes: 
Greeting! maintainers, please consider this contribution of mine under hacktoberfest 2022.
And as always, keep up the good work, this repo of yours is a life saver for about last 1 and a half year, if time allows me I would like to contribute more to this repo :smiley: .

docs: update a logically wrong doc comment

---

CMakeLists.txt
divide_and_conquer/CMakeLists.txt

- Add CMakeLists for the `divide_and_conquer` directory.
Notes:

feat: add CMakeLists for the `divide_and_conquer` directory

---

others/stairs_pattern.cpp

when we propose 2 backslash then it doesn't take it as a comment and gets printed
Notes:

Backslash was not printing

---

data_structures/stack_using_queue.cpp

- `data_strcutres` -> `data_structures`.
Notes:

chore(fix): `data_strcutres` -> `data_structures`

---

DIRECTORY.md
sorting/quick_sort.cpp

- Improve the `quick_sort.cpp` algorithm.
Notes:

[feat/docs]: improve the `quick_sort.cpp` algorithm

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/stale.yml
CONTRIBUTING.md
README.md

Discord links updated.

---

graphics/CMakeLists.txt

- Update FreeGLUT to v3.2.2.
- Closes #2398.
Notes:

chore: update FreeGLUT to v3.2.2

---

DIRECTORY.md
bit_manipulation/power_of_2.cpp
data_structures/avltree.cpp

This PR removes a memory leak in [`avltree.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/7c090481da16a3b97dcd6e1c1dd8cb1ad2951736/data_structures/avltree.cpp). Two things were done:
- the [_new node_ is created](https://github.com/vil02/C-Plus-Plus/blob/2decd5e04cddf335f661c77c9a39c4a134dd6928/data_structures/avltree.cpp#L70) only if `root == nullptr`,
- added the function [`deleteAllNodes`](https://github.com/vil02/C-Plus-Plus/blob/2decd5e04cddf335f661c77c9a39c4a134dd6928/data_structures/avltree.cpp#L125).
Notes: 
_Quick fix_ of a memory leak in [`avltree.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/7c090481da16a3b97dcd6e1c1dd8cb1ad2951736/data_structures/avltree.cpp).

fix: remove memory leak in `avltree.cpp`

---

DIRECTORY.md
math/eratosthenes.cpp

- Add Sieve of Eratosthenes.
- Originally created by @thechubbypanda. Thanks!
Notes:

feat: add Sieve of Eratosthenes (originally by @thechubbypanda)

---

.github/workflows/codeql.yml

- Update the CodeQL workflow (from the [original repository](https://github.com/github/codeql-action)).
Notes:

chore: update the CodeQL workflow

---

sorting/stooge_sort.cpp

feat: add Stooge sort algorithm

---

CONTRIBUTING.md
DIRECTORY.md

- Add self-test examples in the contributing guidelines.
- Closes #2414.
Notes:

docs: add self-test examples

---

data_structures/segment_tree.cpp

I added the segment tree data structure. This allows point updates and range queries with associative operations.

feat: Segment Tree Data Structure

---

dynamic_programming/longest_palindromic_subsequence.cpp

- Improve `longest_palindromic_subsequence.cpp`.
- Add missing parameter/return statement documentation.
- Add namespace for consistency.
- Add a link that explains the algorithm.
Notes:

docs: improve `longest_palindromic_subsequence.cpp`

---

DIRECTORY.md
others/kelvin_to_celsius.cpp

- Add Kelvin to Celsius conversion algorithm.
Notes:

feat: add Kelvin to Celsius conversion algorithm

---

CMakeLists.txt
cpu_scheduling_algorithms/CMakeLists.txt

- Add `cpu_scheduling_algorithms` to CMake.
Notes:

chore: add `cpu_scheduling_algorithms` to CMake

---

CMakeLists.txt
DIRECTORY.md
games/CMakeLists.txt
games/memory_game.cpp

- Add memory game.
- Add a new games folder (#1997).
Notes:

feat: add memory game and a games folder

---

.github/workflows/awesome_workflow.yml
.github/workflows/directory_writer.yml

- Use directory workflow from the `scripts` repository.
- This contributes to #2437.
Notes:

feat: use directory workflow from the `scripts` repository

---

CMakeLists.txt
physics/CMakeLists.txt

- Add the `physics` folder to CMake lists.
Notes:

feat: add `physics` to CMake lists

---

DIRECTORY.md
hashing/sha256.cpp

Added implementation of SHA-256 Hashing Algorithm
Notes:

feat: Add SHA-256 hashing algorithm

---

CMakeLists.txt

Updated CMake to use a newer version. It's set to the same as the C repo.
- ~~[ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)~~
- ~~[ ] Added tests and example, test must pass~~
- ~~[ ] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)~~
- ~~[ ] Relevant documentation/comments is changed or added~~
Notes:

feat: update cmake to use a newer version

---

.github/pull_request_template.md

Fix wrong contributing link (#2502)

---

range_queries/fenwick_tree.cpp

- Improve the Fenwick Tree algorithm.
Notes:

[feat/docs]: improve Fenwick Tree algorithm

---

greedy_algorithms/dijkstra.cpp

- Improve the Dijkstra algorithm.
- Originally initiated in #2490.
Notes:

[feat/docs/fix]: improve the Dijkstra algorithm

---

.github/workflows/awesome_workflow.yml
.github/workflows/codeql.yml
.github/workflows/directory_writer.yml
.github/workflows/gh-pages.yml

The `actions/checkout@v4` was recently [released](https://github.com/actions/checkout/releases/tag/v4.0.0). This PR makes a suitable update.
Notes: 
Update `actions/checkout` to `v4`.

chore: update `actions/checkout` to `v4`

---

.github/workflows/awesome_workflow.yml

Converting awesome-ci's builds to parallel has resulted in:
- ~35% decrease in compiling time on [ubuntu-latest](https://github.com/realstealthninja/C-Plus-Plus/actions/runs/10594413990/job/29358007774)
- ~33% decrease in compiling time on [windows-latest](https://github.com/realstealthninja/C-Plus-Plus/actions/runs/10594413990/job/29358008064)
- ~58% decrease in compiling time on [macOS-latest](https://github.com/realstealthninja/C-Plus-Plus/actions/runs/10594413990/job/29358008341)
Notes:

chore: Make CI builds parallel

---

.github/workflows/gh-pages.yml

Same as TheAlgorithms/Rust#647 - it contains the description of the problem, which this PR solves.
Notes: 
Properly evaluates the `GITHUB_ACTOR` variable.

fix: use `GITHUB_ACTOR` in `git config`

---

data_structures/bloom_filter.cpp

Adds missing `const`.
Notes: 
A const reference should be used in such case.

style: add missing `const` in `bloom_filter.cpp`

---

data_structures/morrisinorder.cpp

[`morrisinorder.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/d74f4d33ea84ef2ff618f09d592aa05effecb3d1/data_structures/morrisinorder.cpp) has a memory leak. This PR is a _quick fix_ of it.
Notes: 
Removes a memory leak from [`morrisinorder.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/d74f4d33ea84ef2ff618f09d592aa05effecb3d1/data_structures/morrisinorder.cpp).

fix: memory leak in `morrisinorder.cpp`

---

search/median_search2.cpp

Continuation of #2723.
Notes: 
Adds missing `const`s to [`median_search2.cpp`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/a0b7dee79ec0523534bee9b0131bb60b1e0d76fe/search/median_search2.cpp).

style: add missing `const` in `median_search2.cpp`

---

ciphers/base64_encoding.cpp
sorting/recursive_bubble_sort.cpp

This PR removes some unused includes of the `array` header.
Similar to #2945.
Notes: 
Removed unused `array` includes.

style: remove unused `array` includes

---

README.md

The compiler versions mentioned in the readme are not accurate and hence needs to be changed.
This pr updates the Readme file and changes the versions to the ones seen in the awesome workflow
Notes: updated versions in readme

doc: change the versions in the readme to their latest used in the repository

---

ciphers/uint128_t.hpp
ciphers/uint256_t.hpp

The aim of this PR is to resolve some of the `-Wunused-parameter` warnings.
Notes: 
Resolves all of the `-Wunused-parameter` in `ciphers/`.

style: resolve `-Wunused-parameter`

---

graph/max_flow_with_ford_fulkerson_and_edmond_karp_algo.cpp

`is_path_found` is essentially not used. This PR removes it.
Notes: 
Remove an unused variable `is_path_found` from `graph/max_flow_with_ford_fulkerson_and_edmond_karp_algo.cpp`.

style: remove unused variable

---

data_structures/cll/cll.h

Fixed "Cicular" -> "Circular"
Notes:

doc: fix typo in ccl.h

---

math/number_of_positive_divisors.cpp

Helps with #2753
It makes this file more CI-friendly (i.e. can help with #2753) - now it can be run without any user interaction.
Notes: 
Removes redundant `std::cin`.

style: remove interaction with the user
